# Generated by Django 3.1.1 on 2021-04-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20210408_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pengumuman',
            name='description',
            field=models.TextField(),
        ),
    ]
