# Generated by Django 3.1.1 on 2021-04-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20210408_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumuman',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='pengumuman',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
