# Generated by Django 3.1.1 on 2021-04-09 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20210408_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengumuman',
            name='files',
        ),
        migrations.CreateModel(
            name='PengumumanFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, max_length=255, null=True, upload_to='files/')),
                ('pengumuman_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.pengumuman')),
            ],
        ),
    ]
