# Generated by Django 3.1.1 on 2021-04-09 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20210409_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengumumanfiles',
            old_name='pengumuman_id',
            new_name='pengumuman',
        ),
    ]
