# Generated by Django 3.1.1 on 2021-04-12 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_berita'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeritaFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, max_length=255, null=True, upload_to='files/')),
                ('berita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.berita')),
            ],
        ),
    ]
