# Generated by Django 3.1.1 on 2021-04-12 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_tautanaplikasi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TautanAplikasi',
            new_name='LinkApps',
        ),
    ]
