# Generated by Django 3.1.1 on 2021-04-12 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20210412_1021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkApps',
            new_name='LinkApp',
        ),
    ]
