# Generated by Django 3.1.1 on 2021-04-12 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20210412_1022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BeritaFiles',
            new_name='BeritaFile',
        ),
        migrations.RenameModel(
            old_name='PengumumanFiles',
            new_name='PengumumanFile',
        ),
    ]
