# Generated by Django 3.1.1 on 2021-04-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20210412_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Visi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visi', models.TextField()),
            ],
        ),
    ]
