# Generated by Django 3.1.1 on 2021-04-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_tugaskewenangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TugasUKPBJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tugas', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='TugasKewenangan',
            new_name='KewenanganUKPBJ',
        ),
        migrations.RenameField(
            model_name='kewenanganukpbj',
            old_name='tugas',
            new_name='kewenangan',
        ),
    ]
