# Generated by Django 3.1.1 on 2021-04-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20210413_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrukturOrganisasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('gambar', models.ImageField(upload_to='')),
            ],
        ),
    ]
