# Generated by Django 3.1.1 on 2021-04-13 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_probis_sop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sop',
            name='probis',
        ),
        migrations.DeleteModel(
            name='Probis',
        ),
        migrations.DeleteModel(
            name='SOP',
        ),
    ]
