# Generated by Django 3.1.1 on 2021-04-13 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_probis_sop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='probis',
            old_name='probis',
            new_name='sop',
        ),
    ]
