# Generated by Django 3.1.1 on 2021-04-13 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20210413_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probis',
            name='sop',
        ),
        migrations.AddField(
            model_name='sop',
            name='probis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.probis'),
        ),
    ]
