# Generated by Django 3.1.1 on 2021-04-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_filestandardokumen_standardokumen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileStandarDokumen',
            new_name='StandarDokumenFile',
        ),
    ]
