# Generated by Django 3.1.1 on 2021-04-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_auto_20210413_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StandarDokumenFile',
        ),
    ]
