# Generated by Django 3.1.1 on 2021-04-13 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_delete_standardokumenfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandarDokumenFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='files/')),
                ('dokumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.standardokumen')),
            ],
        ),
    ]
