# Generated by Django 3.1.1 on 2021-04-14 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_standardokumenfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='files/')),
                ('dokumen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.standardokumen')),
            ],
        ),
        migrations.DeleteModel(
            name='StandarDokumenFile',
        ),
    ]
