# Generated by Django 3.1.1 on 2021-04-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_regulasi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regulasi',
        ),
    ]
