# Generated by Django 3.1.1 on 2021-04-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_delete_regulasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('file', models.FileField(max_length=255, upload_to='files/')),
            ],
        ),
    ]
