# Generated by Django 3.1.1 on 2021-04-16 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_regulasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulasi',
            name='description',
        ),
    ]
