# Generated by Django 3.1.1 on 2021-04-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_useradmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradmin',
            name='profil_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
