# Generated by Django 3.1.1 on 2021-04-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_useradmin_profil_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradmin',
            name='profil_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
